***************
*** 3,9 ****
  
  GCC=gcc
  
- TARGETS = xor_train xor_test xor_test_fixed simple_train steepness_train simple_test robot mushroom cascade_train
  DEBUG_TARGETS = xor_train_debug xor_test_debug xor_test_fixed_debug cascade_train_debug
  
  all: $(TARGETS)
--- 3,9 ----
  
  GCC=gcc
  
+ TARGETS = xor_train xor_test xor_test_fixed simple_train steepness_train simple_test robot mushroom cascade_train scaling_test scaling_train
  DEBUG_TARGETS = xor_train_debug xor_test_debug xor_test_fixed_debug cascade_train_debug
  
  all: $(TARGETS)
***************
*** 15,21 ****
  	$(GCC) -O3 -DFIXEDFANN $< -o $@ -lm -lfixedfann
  
  clean:
- 	rm -f $(TARGETS) $(DEBUG_TARGETS) xor_fixed.data *.net *~ *.obj *.exe *.tds
  
  runtest: $(TARGETS)
  	@echo
--- 15,21 ----
  	$(GCC) -O3 -DFIXEDFANN $< -o $@ -lm -lfixedfann
  
  clean:
+ 	rm -f $(TARGETS) $(DEBUG_TARGETS) xor_fixed.data *.net *~ *.obj *.exe *.tds noscale.txt withscale.txt scale_test_results.txt
  
  runtest: $(TARGETS)
  	@echo
